### ISSUE TITLE
--bind-dns-address ,not working

### ISSUE THREAD

**Issue by golden777** [webfolderio/wget-windows#1]
wget --bind-dns-address 1.1.1.1 https://www.cloudflare.com
------------
Resolving www.cloudflare.com (www.cloudflare.com)... failed: No IPv4/IPv6 addresses for host.
wget: unable to resolve host address 'www.cloudflare.com'

**Comment by webfolderio** [comment]
Hi @golden777, please update your wget version to 1.21.1 and retry your command.

**Comment by golden777** [comment]
thanks,it runs, but the result is incorrect
wget --bind-dns-address 1.1.1.1 https://www.cloudflare.com
no matter change the 1.1.1.1 to any ip address ,it alwaly return the default resualt
