### ISSUE TITLE
Update to 1.21.2 and also offer 32-bit builds...

### ISSUE THREAD

**Issue by Vangelis66** [webfolderio/wget-windows#2]
Hi 😄 

Many thanks for your efforts thus far; highly appreciated 👍 ...

**Wget** has been recently updated to v[1.21.2](https://github.com/mirror/wget/releases/tag/v1.21.2) ; would you be kind enough to update your builds to the new version? 
Additionally, what I'd really like to see is **also x86 (32-bit) static builds**, as I (and, no doubt, many others 😉 ) still keep _slightly older_ laptops (otherwise very functional 😉) with **Windows 32-bit OSes**...

Thanks in anticipation, take the greatest of care 😃 ...

**Comment by webfolderio** [comment]
32 Bit build added which supports OpenSSL.
