### ISSUE TITLE
[FYI] GnuTLS 3.7.5

### ISSUE THREAD

**Issue by CharlesMengCA** [webfolderio/wget-windows#6]
To compile with GnuTLS 3.7.5, you need to add -lpthread to the LIBS.

Refer:
https://github.com/CharlesMengCA/wget-windows/commit/9e4353ac4cb9737f3f510e663afd3c0bb0dd5433

**Comment by webfolderio** [comment]
Thank you @CharlesMengCA gnutls is updated to 3.7.6
