### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by wbtcpip2** [webfolderio/wget-windows#7]
wget fails to download this file wget https://api.spreaker.com/v2/episodes/6645151/download.mp3 always error 403

note that if i open that url on any browser it works

**Comment by garoto** [comment]
`--no-iri` is a workaround.

**Comment by webfolderio** [comment]
**Solution 1**
Thanks for suggestion @garoto 

`wget --no-iri https://api.spreaker.com/v2/episodes/6645151/download.mp3`

**Solution 2**

`wget --local-encoding=utf-8  https://api.spreaker.com/v2/episodes/6645151/download.mp3`

**Solution 3 (configure the global setting to disable iri)**

create .wgetrc and paste the write the following line

```
iri=no
```
[https://www.gnu.org/software/wget/manual/wget.html#Startup-File](https://www.gnu.org/software/wget/manual/wget.html#Startup-File)

**Comment by wbtcpip2** [comment]
Thank you

 

Da: garoto ***@***.***> 
Inviato: sabato 21 maggio 2022 04:29
A: webfolderio/wget-windows ***@***.***>
Cc: wbtcpip2 ***@***.***>; Author ***@***.***>
Oggetto: Re: [webfolderio/wget-windows] error 403 (Issue #7)

 

--no-iri is a workaround.
